### PR TITLE
Replace tabs with spaces. Without this ruby complains when running test tasks with warnings enabled due to 'warning: mismatched indentations at 'end'

### LINKED ISSUE #45: warning: mismatched indentations at 'end' with 'class' warnings due to use of tabs
If ruby tests are run with verbose or warnings turned on the test run will output the following warnings from `coco`.

```
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/coco-0.13.0/lib/coco/formatter/context.rb:22: warning: mismatched indentations at 'end' with 'class' at 4
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/coco-0.13.0/lib/coco/formatter/context.rb:53: warning: mismatched indentations at 'end' with 'class' at 25
```

This is due to the use of tabs instead of spaces (inconsistently) in a couple of files.

### PR DESCRIPTION
**Pull request by grempe**
Fix #45

### CODE REVIEW

**Comment by grempe** [comment]
^^^ The CI build just failed, but not due to my changes. See the details:

```
An error occurred while installing coco (0.13.0), and Bundler cannot continue.
Make sure that `gem install coco -v '0.13.0'` succeeds before bundling.
```

**Comment by lkdjiin** [comment]
Thank you for this one. But please use the development branch: https://github.com/lkdjiin/coco#contributing

**Comment by grempe** [comment]
Well, I think I'll leave that to you since your development branch is about five commits behind master and that fix up should not be in a pull request. :)

screen shot on 2016-03-26 at 19_44_15

**Comment by lkdjiin** [comment]
oh you're right! Thank you for opening my eyes. I'll fix that crap.

**Comment by lkdjiin** [comment]
Thanx again to have spotted both issues

**Comment by grempe** [comment]
Lots of changes.  My test run is clean now with 0.14.0 :100:

**Pull request closed without merging**
